### ISSUE TITLE
Provide info on adding include and linker in Xcode 8

### ISSUE THREAD

**Issue by proyb6** [naithar/MagickWand#13]
I have difficulty setting up in Xcode 8, which keep saying a particular header file is not found. Appreciate if you could provide a guide for working in Xcode.

**Comment by naithar** [comment]
@proyb6 can you please check if new README covers the steps needed for XCode project building?

**Comment by JohnKnust** [comment]
it's still a problem :/ it can't be build
Header '/usr/local/include/ImageMagick-6/wand/MagickWand.h' not found

**Comment by naithar** [comment]
Using the shell command in README file under `XCode Setup` section creates the XCode project that uses MagickWand library files and does not cause errors.
