### ISSUE TITLE
PDF Support

### ISSUE THREAD

**Issue by drewag** [naithar/MagickWand#16]
I am having trouble getting PDFs to work. I assume the problem is that it is not linking properly to ghostscript. Do you know how to do this properly or do you know how to properly load a PDF?

More specifically I am getting a "false" returned from MagickReadImageBlob

I have run: `brew install imagemagick@6 --with-ghostscript`
Then I added `link "gs.9"` to the module map

My impression is that this is now linking in ghostscript but perhaps something extra needs to be done to imagemagick/magickwand to make use of it?

I have also tried setting the "filename" of the wand to a PDF before calling MagickReadImageBlob but that did not seem to help.

Any ideas?

**Comment by drewag** [comment]
Ok I think I figured it out (at least for mac). The `--with-ghostscript` does not seem to be configured correctly in home-brew. It does not configure ImageMagick with the `--with-gslib=yes` option that is required to link against ghostscript. To fix this, I ran `brew install -i imagemagick@6 --with-ghostscript` and manually added the `--with-gslib=yes` option when running configure. Now it can process PDFs successfully. I will close this once I confirm everything is working on Linux as well.

**Comment by naithar** [comment]
@drewag thanks for investigation. Care to make a PR?  
As far as I can tell all the problems with imagemagick not being able to process specific format is from dependencies not being installed. It looks like thats the same problem you have faced.
Previously there was a build script, but currently it need some work to build everything correctly (after some point it stoped processing even jpeg/png images).

**Comment by naithar** [comment]
Using the `install-imagemagick.sh` script solves the issue with reading PDF files. 
The tests were added to check this.
