### ISSUE TITLE
MagickGetImageBlob returns nil 

### ISSUE THREAD

**Issue by JohnKnust** [naithar/MagickWand#17]
Hi there,
after try running the test I figured out that all 'ImageWandTests.swift' tests fail.
In the one listed below I figured some more informations out. Hopefully someone has a solution.

Thanks

In `func testInitWithData()` this fails:
`XCTAssertNotNil(imageWand!.data, "ImageWand should have Data")`

Here: ImageWand.swift in line 41 it returns nil:
`guard let imageBlob = MagickGetImageBlob(self.pointer, &size) else {
            return []
        }`

<img width="606" alt="screen shot 2017-06-08 at 20 05 51" src="https://user-images.githubusercontent.com/12036586/26943604-716b409a-4c86-11e7-8ba9-c2a3b781f766.png">

**Comment by naithar** [comment]
There could be a problem with your ImageMagick installation. 
The last time the same problem happened the reason was in PNG library dependency not being installed.

**Comment by naithar** [comment]
I've tried to cover dependency installation for macOS in the readme, but seems like it's not completely working.

**Comment by JohnKnust** [comment]
I will give it later one more try :]
